### PR TITLE
Support multipart/form-data requests

### PR DESCRIPTION
**Pull request by iamdeit**
In order to support multipart/form-data requests to upload files we need to change he behavior of the raw parser. Also, event.data should not convert the body to string in these cases.

### CODE REVIEW

**Comment by mikefarah** [comment]
Hmm only issue I see here is that it diverges from what kubeless does:

https://github.com/kubeless/runtimes/blob/master/stable/nodejs/kubeless.js

**Comment by iamdeit** [comment]
There is a PR there waiting to be merged with the same funcionality

**Comment by mikefarah** [comment]
LGTM - just needs to merge in the limit parameters to match https://github.com/kubeless/runtimes/blob/master/stable/nodejs/kubeless.js

**Comment by iamdeit** [comment]
@mikefarah Already made the changes. Thanks!

**Pull request merged**
